version: "3.8"

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "2000:2000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./app:/app
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/:/etc/nginx/certs/  # Mount certificate files
    ports:
      - "1280:1280"   # Expose HTTP for redirection
      - "12443:12443" # Expose HTTPS
    depends_on:
      - flask_app
    restart: always
